### ISSUE TITLE
Register-SecretVault allows registering same extension vault more than once

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/SecretManagement#51] opened 2020-10-09 17:43 UTC
Seems like it should detect that an extension vault has already been registered and quietly succeed rather than registering more than once.

**Comment by adityapatwardhan** [comment] 2020-10-09 18:10
In addition to that it allows the -DefaultVault to be used even if an vault is registered as default.

**Comment by PaulHigin** [comment] 2020-10-09 18:36
@SteveL-MSFT  Please provide repro steps.  We already check vault name and allow only one registered, so I assume you mean we should disallow registering the same extension vault under different names?

**Comment by daxian-dbw** [comment] 2020-10-09 19:42
> I assume you mean we should disallow registering the same extension vault under different names?

I think it could be useful to allow registering the same extension vault under different names, so a user's secrets can be categorized.

**Comment by SteveL-MSFT** [comment] 2020-10-09 19:54
@PaulHigin yes, same vault extension under different names.  In my case, I had just installed a newer version of SecretStore and re-registered it.  When enumerating the vaults, I saw I had registered SecretStore twice under different names and one was default and the other wasn't.  Since the secrets are stored in the same vault, I don't think there's a use case to support this.

**Comment by daxian-dbw** [comment] 2020-10-09 21:03
> Since the secrets are stored in the same vault, I don't think there's a use case to support this.

If the secrets are stored in the same place for both registered vault, then I agree that we should disallow registering the same extension more than once.

**Comment by SydneyhSmith** [comment] 2020-10-12 21:43
Also related: https://github.com/PowerShell/SecretStore/issues/35

**Comment by SteveL-MSFT** [comment] 2020-10-16 17:55
A use case we discussed is for extension vaults that support partitions or namespaces.  In this case, it would make sense to allow multiple registrations where each one is registered to a specific namespace within that vault.

**Comment by SydneyhSmith** [comment] 2020-11-10 23:24
Closing as by design-- a user may want to use the say extension vault multiple times with different configurations

**Closed by SydneyhSmith** 2020-11-10 23:24 UTC
Labels: question
