### ISSUE TITLE
Module Manifest HelpInfoURI

### ISSUE THREAD

**Issue by tommymaynard** [PowerShell/SecretManagement#125] opened 2021-03-29 15:34 UTC
**FYI**: The HelpInfoURI ([https://aka.ms/ps-modules-help](https://aka.ms/ps-modules-help)) doesn't lead anywhere useful. My last attempt to follow this link results in the below message.

_BlobNotFoundThe specified blob does not exist. RequestId:b1451417-201e-009b-21b0-241835000000 Time:2021-03-29T15:32:36.9783072Z_

**Comment by tommymaynard** [comment] 2021-03-29 16:18
Thank you @PaulHigin. I wasn't after the help that one might've expected been behind the link. I just tried it, it didn't work, and wanted to pass along my finding.

**Comment by sdwheeler** [comment] 2021-03-29 16:22
The HelpInfoUri links have never been browsable. That is by design. They point to a folder location that is not browsable. But `Update-Help` works. I just tested it.

@PaulHigin you can close this issue.

**Closed** 2021-03-29 16:23 UTC
