### ISSUE TITLE
-AsPlainText with PSCredential secrets... is this a layering problem?

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/SecretManagement#39] opened 2020-09-21 18:02 UTC
![image](https://user-images.githubusercontent.com/2644648/93803265-6d747a80-fbf9-11ea-923c-1f81771bb4fe.png)

Right now, it doesn't do anything.

It makes sense because it's returning a PSCredential which can only be represented by a `string` username and `SecureString` password...

So either we leave it as is and `-AsPlainText` only works for some secret types... or

1. We have some way to "show" the password of a PSCredential (maybe we attach a Note property or just return a username,password pscustomobject...)
2. We remove `-AsPlainText` because `ConvertFrom-SecureString` is already available for this usecase

**Comment by PaulHigin** [comment] 2020-09-21 18:07
'-AsPlainText' doesn't apply to PSCredential and byte[] secret types.  I don't think it is worth emitting a warning in this case and the current behavior is to simply ignore it.

**Comment by PaulHigin** [comment] 2020-09-22 17:33
Closing this as by design.

**Closed by PaulHigin** 2020-09-22 17:33 UTC
Labels: bug, wontfix
