### ISSUE TITLE
Request: Register-SecretVault should call Test-SecretVault of the implementing extension in host UI Thread

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#43] opened 2020-09-22 06:13 UTC
`Register-SecretVault` does not appear to currently call any validation to the extension to make sure the `VaultParameters` are correct, for instance if a file path is correct. This also would give the extension the opportunity to do any registration of the vault if required, such as fetching an API key, etc.

EDIT: From what I'm seeing it does actually call it, but it calls it in a separate C# invocation, which disables all the host UI and other items that could be part of a test (e.g. prompting for the database path if one wasn't supplied). Further, Test-SecretVault are difficult to debug since no stacktrace is provided, only $error[0].exception.innerexception to maybe hint at what went wrong.

**Comment by SydneyhSmith** [comment] 2020-09-22 22:09
@JustinGrote we made the choice to separate the Testing of the vault from Registration in order to facilitate debugging (you may not want registration to fail just because the vault isnt currently available)...would love to hear more about why this would be useful though!

**Comment by JustinGrote** [comment] 2020-09-22 22:13
@SydneyhSmith I feel this is something that can be controlled by VaultParameters, for instance an extension can have "Offline" VaultParameter to skip parts of the check if that offline registration is required. Maybe instead of it calling Test-SecretVault directly it could be a separate function like Test-SecretVaultIsValid that is specifically related to that piece so test-secretvault still always assumes it is onlin

Otherwise my workaround is sufficient in that I just call Test-SecretVault at the top of every other function :)

**Comment by SydneyhSmith** [comment] 2020-11-10 23:31
Thanks we are going to close this as by design

**Closed by SydneyhSmith** 2020-11-10 23:31 UTC
Labels: feature_request
