### ISSUE TITLE
VaultNameCompleter doesn't handle vaults with spaces in their names

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#96] opened 2021-01-16 07:48 UTC
If a vault has a space in its name, VaultNameCompleter does not wrap it in quotes when it is tab-selected

![Capture](https://user-images.githubusercontent.com/15258962/104806420-37509d00-578c-11eb-8338-3eb4ca0a0f53.gif)

**Comment by PaulHigin** [comment] 2021-01-19 21:24
Duplicate of #91

**Closed by PaulHigin** 2021-01-19 21:24 UTC
