### ISSUE TITLE
Creating additional vault duplicates secrets

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/SecretManagement#101] opened 2021-02-02 16:12 UTC
I thought that I could create(register) a different vault. Unless I'm have missed something, every time I register a new vault all of my secrets get duplicated.  

So, how can I have separate vaults to hold a different set of secrets?

![SecretVaultIssue_0`1_2021-02-01_13-15-50](https://user-images.githubusercontent.com/19892435/106628138-7da54a80-6547-11eb-9c3b-48ed92ca0536.png)

**Comment by JustinGrote** [comment] 2021-02-07 01:43
I don't think the builtin secretstore was currently designed with multiple vaults in mind.
https://github.com/PowerShell/SecretStore

Other vaults support multiple targets, like my Chromium vault or Keepass vault or the Azure Keyvault vault

**Comment by MaximoTrinidad** [comment] 2021-02-07 04:12
@JustinGrote,

So, it a bug? Or, can it support having multiple Vaults in the future?
that would be my feature request.

**Comment by PaulHigin** [comment] 2021-03-03 22:42
This is by design.  The Microsoft.PowerShell.SecretStore extension vault stores secrets locally based on the current user account.  For more information please see the design document:
https://github.com/PowerShell/SecretStore/tree/master/Docs

We decided to allow an extension vault to be registered multiple times because some vault types may allow different configurations (unlike SecretStore).  For example an AzKeyVault based vault may allow different remote vaults based on subscription id.

But both SecretStore and CredMan vaults store secrets based on current user account and so should only be registered once per user.

**Comment by PaulHigin** [comment] 2021-03-03 22:45
Closing this because I believe this is answered.  Feel free to reopen if you have more concerns.

**Closed by PaulHigin** 2021-03-03 22:45 UTC
