### ISSUE TITLE
Register-SecretVault positional parameters unintuitive

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/SecretManagement#49] opened 2020-10-09 17:36 UTC
I tried to omit the parameter names when using `Register-SecretVault`, but the positions didn't work out as I expected (given the example in the blog post, and other cmdlets that accept a name/key and a value):

```
> Register-SecretVault SecretStore Microsoft.PowerShell.SecretStore -DefaultVault
Register-SecretVault: Could not load and retrieve module information for module: SecretStore with error : The specified module 'SecretStore' was not loaded because no valid module file was found in any module directory..
```

**Comment by SydneyhSmith** [comment] 2020-10-12 21:04
Thanks @rjmholt  we did this in response to other input that users may not want to provide a friendly name so the module name is set to position zero...if I updated my blog do you think this would help? Or do you think it would make more sense to have the friendly name as position zero?

**Comment by rjmholt** [comment] 2020-10-12 22:41
Ah, I see. That makes sense. I think my ideal would be to document a couple of variant examples demonstrating its intended function.

**Comment by PaulHigin** [comment] 2020-11-03 18:58
Closing as 'by design'.

**Closed by PaulHigin** 2020-11-03 18:58 UTC
Labels: question
