### ISSUE TITLE
Register-SecretVault is misleading

### ISSUE THREAD

**Issue by smoofy** [PowerShell/SecretManagement#92] opened 2021-01-13 14:20 UTC
```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Binary     0.9.0                 Microsoft.PowerShell.SecretManagement
Binary     0.9.0                 Microsoft.PowerShell.SecretStore
```

According documentation `Register-SecretVault` is intended to "Registers a SecretManagement extension vault".
In fact an extension vault can be register multiple time with a different name but it still act as it's the same vault (tested with SecretStore extension).

I understand that there is no multiple vault support for a same extension vault.
At first, I think it was the way it was designed: ModuleName for the extension vault and Name for the vault Name.

My proposal is to add a multiple vault support attribute and allow extension vault to choose if multiple vault is supported or not as it's possible to create multiple SecretStore vault file and we can only have one CredManStore. When a vault extension does not support multiple vault, trying to register more than once will lead to an error.

This way when using many script with credential management, each script can work with it own vault and avoid potential secret conflict in the store.

**Comment by JustinGrote** [comment] 2021-01-14 23:46
This basically already exists for vault authors with VaultParameters. Your vault could allow for a "Prefix" parameter for instance to prefix all secrets. You could also implicitly segregate based on Name which is what I do in my `SecretManagement.Keepass` module. 

In my opinion, Name can be used as a distinction for multiple secret vaults if only a single vault is allowed (and your implementation can use whatever metadata you need to inform that), and if you need more than that, it can be supplied via vaultparameters.

**Comment by SydneyhSmith** [comment] 2021-01-19 22:18
Thanks this looks like a duplicate of https://github.com/PowerShell/SecretManagement/issues/51

**Closed by SydneyhSmith** 2021-01-19 22:18 UTC
